# Built with Jekyll 3.2.0

# Setup
title:               reniew's blog
tagline:             'cs and deep learning'
description:         'cs and deep learning'
url:                 https://reniew.github.io
baseurl: 
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _sass
paginate: 5
paginate_path: '/contents/page:num'
permalink: pretty
version: 1.0.0

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Contents:
    - '/contents/'
    - { Categories: '/contents/categories/' }
  About:
    - '/about/'

# About/contact
author:
  name: reniew
  description: <strong>JungHyun</strong>
  gravatar: acbbb7e6ecc45391c6d4d9953b5d27e7 # md5 hash of your email address
  contact:
    #linkedin:  <hide>
    github:    https://github.com/reniew
    facebook:  https://www.facebook.com/people/%EC%A1%B0%EC%A4%91%ED%98%84/100001883067095
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:reniew1@nate.com

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."


# Plugins
mathjax: true
google_analytics_token: 'UA-122743068-1'
disqus_short_name: 'reniew'
